# Generated by Django 5.2.8 on 2025-11-14 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_booking_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('confirmed', 'Подтверждена'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='pending', max_length=20, verbose_name='Статус')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pages.booking', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Статус записи',
                'verbose_name_plural': 'Статусы записей',
            },
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterModelOptions(
            name='privacypolicy',
            options={'verbose_name': 'Политика конфиденциальности', 'verbose_name_plural': 'Политика конфиденциальности'},
        ),
        migrations.RemoveField(
            model_name='consentform',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='consentform',
            name='version',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='effective_date',
        ),
        migrations.RemoveField(
            model_name='privacypolicy',
            name='version',
        ),
    ]
